<?php
/**
 * Copyright © Risecommerce (support@risecommerce.com). All rights reserved.
 * 
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
?>
<?php
$helper = $this->helper(\Risecommerce\Blog\Helper\Data::class);
?>

<?php if (!$helper->isOriginRcLazyLoadEnable()) { ?>
    <script>
        if (window.require) {
            require(['jquery', 'Risecommerce_Blog/js/lib/rcblogunveil', 'domReady!'], function($){
                $('.rcblogunveil').rcblogunveil();
            });
        } else {
            /* e.g. hyva theme */
            document.addEventListener("DOMContentLoaded", function(){
                var items =  document.getElementsByClassName('rcblogunveil');
                var el, url;
                if (items.length) {
                    for (var i=0; i<items.length;i++) {
                        el = items[i];
                        url = el.getAttribute('data-original');
                        if (!url) {
                            continue;
                        }
                        if ('IMG' == el.tagName) {
                            el.src = url;
                        } else {
                            el.style.backgroundImage = "url('" + url  + "')";
                        }
                    }
                }
            });
        }
    </script>
<?php } ?>

