<?php
/**
 * Copyright © Risecommerce (support@risecommerce.com). All rights reserved.
 * 
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post comments template
 *
 * @var $block \Risecommerce\Blog\Block\Post\View\Comments
 */
?>
<script src="https://apis.google.com/js/plusone.js"></script>
<div id="rcblog_gcomments" data-width="100%" height="200px"></div>
<script>
    gapi.comments.render('rcblog_gcomments', {
        href: '<?= $block->escapeUrl($block->getPost()->getPostUrl()) ?>',
        first_party_property: 'BLOGGER',
        view_type: 'FILTERED_POSTMOD'
    });
</script>