<?php
/**
 * Copyright © Risecommerce (support@risecommerce.com). All rights reserved.
 * 
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog sidebar archive template
 *
 * @var $block \Risecommerce\Blog\Block\Sidebar\Rss
 */
?>
<div class="widget block block-rss" data-bind="scope: 'blog-rss'">
    <div class="block-title">
        <strong>
            <a target="_blank"
               href="<?= $block->escapeUrl($block->getUrl('blog/rss/feed')) ?>">
                <?= $block->escapeHtml(__('RSS Feed')) ?>
            </a>
        </strong>
        <img width="17" height="17" class="rss-icon"
             src="<?= $block->escapeUrl($block->getViewFileUrl('Risecommerce_Blog::images/rss-icon.png')) ?>"
             alt="<?= $block->escapeHtml(__('RSS Feed')) ?>" >
    </div>
</div>
