<?php
/**
 * Copyright © Risecommerce (support@risecommerce.com). All rights reserved.
 * 
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog tag claud sidebar template
 *
 * @var $block \Risecommerce\Blog\Block\Sidebar\TagClaud
 */
?>
<?php $tags = $block->getTags(); ?>

<?php if (count($tags)) { ?>
<div class="widget block block-tagclaud" data-bind="scope: 'tagclaud'">
    <div class="block-title">
        <strong><?= $block->escapeHtml(__('Tags')) ?></strong>
    </div>

    <div class="tagclaud-hld">
    <?php foreach ($tags as $tag) { ?>
        <?php $title = $tag->getTitle() ?>
        <span class="<?= $block->escapeHtml($block->getTagClass($tag)) ?>">
            <a href="<?= $block->escapeUrl($tag->getTagUrl()) ?>" title="<?= $block->escapeHtml($title) ?>">
                <?= $block->escapeHtml($title) ?>
            </a>
        </span>
    <?php } ?>
    </div>
</div>
<?php } ?>
