<?php
/**
 * Copyright © Risecommerce (support@risecommerce.com). All rights reserved.
 * 
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post list toolbar template
 *
 * @var $block \Risecommerce\Blog\Block\Post\PostList\Toolbar
 */
?>
<?php if ($block->getCollection()->getSize()) { ?>
    <?php $pagerHtml = trim( $block->getPagerHtml()) ?>
    <?php if ($pagerHtml) { ?>
        <?php $woj = $block->getWidgetOptionsJson() ?>
        <div class="toolbar toolbar-blog-posts"
        <?= /*@noEscape*/ ($woj) ? 'data-mage-init="'.$woj.'"' : ''; ?>
        >
        <?= /*@noEscape*/ $pagerHtml ?>
        </div>
    <?php } ?>
<?php } ?>
